### ISSUE TITLE
assume connection keep-alive as default

### ISSUE THREAD

**Issue by smatthes42berlin** [Mafematic/42_Webserv#1]
https://github.com/Mafematic/42_Webserv/blob/26b2cbc69d089633aca925884d7d3e72c5e28d7d/src/ServerManager.cpp#L127

If "Connection" header is not defined, the connection will be closed. Default behaviour should be to keep the connection alive.

Suggested solution:

Allow default values in request parser for certain headers, if they are not defined in the request.

**Comment by Mafematic** [comment]
This should be resolved. Connection header is now stores in Request object and also sent back as part of the response to client.
