### ISSUE TITLE
Custom error page

### ISSUE THREAD

**Issue by smatthes42berlin** [Mafematic/42_Webserv#13]
It seems like a custom error page defined on the server level is not used. It works, if the error page is defined on the route level. Is this intended behaviour?

**Comment by Mafematic** [comment]
I think it is fixed. 
My approach is the following: 

I check on route level if there is an index page. 
If not I check if autoindex is on. 
If autoindex is off, I check on server level for index.html
If not index on Server level I check on route level if 404 specified
If 404 not on route, I check on server level, if not on server level I go to default.

**Comment by Mafematic** [comment]
I think now fully solved :)
