### ISSUE TITLE
client max body size not working for post cgi script

### ISSUE THREAD

**Issue by smatthes42berlin** [Mafematic/42_Webserv#14]
Maybe just have to set valid flag when checking

test case:

server {
	listen 10005;
    client_max_body_size 10;

	location /cgi-bin/ {
    	client_max_body_size 10;
		root       ./root/;
		allowed_methods GET POST DELETE;
	}
}

curl -X POST -H "Content-Type: plain/text" --data "BODY IS HERE write something shorter or longer than body limit" 127.0.0.1:10005/cgi-bin/print_env_body.py

**Comment by Mafematic** [comment]
Fixed, working now. :)
