### ISSUE TITLE
Tell client that connection gets closed

### ISSUE THREAD

**Issue by smatthes42berlin** [Mafematic/42_Webserv#3]
https://github.com/Mafematic/42_Webserv/blob/26b2cbc69d089633aca925884d7d3e72c5e28d7d/src/ServerManager.cpp#L42

Put the connection:close header into response, to tell the client that the server is closing the connection.

**Comment by Mafematic** [comment]
This has also be resolved together with the handling of Connection header - keep Alive / Close
